const SUPABASE_URL='https://qmcvzsxtnconqbioiktw.supabase.co';
const SUPABASE_KEY='sb_publishable_uH7Oz5_OdBRGsVkWczufPQ_vr4agAFE';
const client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,teams=[],profiles=[],reports=[],quizQuestions=[],quizSubmissions=[],quizAnswers=[];
const $=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(v||0),sum=(arr,k)=>arr.reduce((a,x)=>a+num(x[k]),0),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const fmtDate=v=>v?new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v+'T12:00:00')):'—';
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function empty(msg){return `<div class="empty">${esc(msg)}</div>`}
function iso(d){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function monday(d=new Date()){const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x}
function rangeForPeriod(){const p=$('periodFilter')?.value||'this_month',today=new Date();if(p==='all')return [null,null];if(p==='custom'){return [$('dateFrom').value||null,$('dateTo').value||null]}
 let s,e;if(p==='this_week'){s=monday(today);e=new Date(s);e.setDate(e.getDate()+6)}else if(p==='last_week'){e=monday(today);e.setDate(e.getDate()-1);s=new Date(e);s.setDate(s.getDate()-6)}else if(p==='this_month'){s=new Date(today.getFullYear(),today.getMonth(),1);e=new Date(today.getFullYear(),today.getMonth()+1,0)}else if(p==='last_month'){s=new Date(today.getFullYear(),today.getMonth()-1,1);e=new Date(today.getFullYear(),today.getMonth(),0)}else{const w=Number(p);s=monday(today);s.setDate(s.getDate()-((w-1)*7));e=today}return [iso(s),iso(e)]}
function filteredReports(){const [s,e]=rangeForPeriod(),team=$('teamFilter')?.value||'';return reports.filter(r=>(!team||r.team_id===team)&&(!s||r.week_start>=s)&&(!e||r.week_start<=e))}
function teamName(id){return teams.find(t=>t.id===id)?.name||'Sem time'}
function leaderForTeam(id){const t=teams.find(x=>x.id===id);return profiles.find(p=>p.id===t?.leader_id)||null}
function execsOfTeam(id){return profiles.filter(p=>p.role==='executive'&&p.team_id===id)}
function scoreEntities(items){const max={contracts:Math.max(0,...items.map(x=>x.contracts)),minutes:Math.max(0,...items.map(x=>x.minutes)),held:Math.max(0,...items.map(x=>x.held)),scheduled:Math.max(0,...items.map(x=>x.scheduled))};return items.map(x=>({...x,score:Math.round(((max.contracts?x.contracts/max.contracts:0)*.4+(max.minutes?x.minutes/max.minutes:0)*.25+(max.held?x.held/max.held:0)*.2+(max.scheduled?x.scheduled/max.scheduled:0)*.15)*100)}))}
function aggregateByTeam(list){return scoreEntities(teams.filter(t=>t.active).map(t=>{const rr=list.filter(r=>r.team_id===t.id);return {id:t.id,name:t.name,leader:leaderForTeam(t.id),scheduled:sum(rr,'meetings_scheduled'),held:sum(rr,'meetings_held'),minutes:sum(rr,'minutes_sent'),contracts:sum(rr,'contracts_closed'),reports:rr.length}}))}
function aggregateByExec(list){return scoreEntities(profiles.filter(p=>p.role==='executive'&&p.active).map(p=>{const rr=list.filter(r=>r.executive_id===p.id);return {id:p.id,name:p.name,email:p.email,team_id:p.team_id,scheduled:sum(rr,'meetings_scheduled'),held:sum(rr,'meetings_held'),minutes:sum(rr,'minutes_sent'),contracts:sum(rr,'contracts_closed'),reports:rr.length}}))}
async function init(){const auth=await client.auth.getSession();session=auth.data.session;if(!session){location.href='login.html';return}const {data:me}=await client.from('profiles').select('role,active').eq('id',session.user.id).maybeSingle();if(me?.role!=='super_admin'||me?.active===false){location.href='portal.html';return}bind();await loadAll()}
async function loadAll(){const [t,p,r,q,s,a]=await Promise.all([client.from('teams').select('*').order('created_at'),client.from('profiles').select('*').order('name'),client.from('weekly_reports').select('*').order('week_start',{ascending:false}),client.from('quiz_questions').select('*').eq('active',true).order('sort_order'),client.from('quiz_submissions').select('*').order('submitted_at',{ascending:false}),client.from('quiz_answers').select('*')]);teams=t.data||[];profiles=p.data||[];reports=r.data||[];quizQuestions=q.data||[];quizSubmissions=s.data||[];quizAnswers=a.data||[];populateFilters();renderAll()}
function populateFilters(){const opts=teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');['teamFilter','execTeamFilter','quizTeamFilter'].forEach(id=>{const el=$(id),old=el.value;el.innerHTML='<option value="">Todos os times</option>'+opts;if([...el.options].some(o=>o.value===old))el.value=old});$('editExecTeam').innerHTML=opts;renderQuizExecFilter()}
function renderAll(){renderOverview();renderTeams();renderExecutives();renderQuiz()}
function renderOverview(){const rr=filteredReports(),teamAgg=aggregateByTeam(rr).sort((a,b)=>b.score-a.score),execAgg=aggregateByExec(rr).sort((a,b)=>b.score-a.score);$('statTeams').textContent=teams.filter(t=>t.active).length;$('statExecs').textContent=profiles.filter(p=>p.role==='executive'&&p.active&&(!$('teamFilter').value||p.team_id===$('teamFilter').value)).length;$('statMeetings').textContent=sum(rr,'meetings_held');$('statMinutes').textContent=sum(rr,'minutes_sent');$('statContracts').textContent=sum(rr,'contracts_closed');
 $('teamPerformance').innerHTML=teamAgg.length?teamAgg.map(t=>`<div class="team-row"><div><strong>${esc(t.name)}</strong><small>Líder: ${esc(t.leader?.name||'Não definido')}</small></div><div class="bar"><i style="width:${t.score}%"></i></div><div class="metric"><b>${t.held}</b><span>reuniões</span></div><div class="metric"><b>${t.minutes}</b><span>minutas</span></div><div class="metric hide-mid"><b>${t.contracts}</b><span>contratos</span></div><div class="metric hide-mid"><b>${t.scheduled}</b><span>agendadas</span></div><div class="score">${t.score}</div></div>`).join(''):empty('Sem dados no período');
 const best=teamAgg[0];$('leaderHighlight').innerHTML=best?`<div class="highlight-card"><span class="badge">LÍDER EM DESTAQUE</span><h3>${esc(best.leader?.name||'Líder não definido')}</h3><p>${esc(best.name)} • índice ${best.score}/100</p><div class="highlight-metrics"><div><span>Contratos</span><b>${best.contracts}</b></div><div><span>Minutas</span><b>${best.minutes}</b></div><div><span>Reuniões</span><b>${best.held}</b></div><div><span>Executivos</span><b>${execsOfTeam(best.id).filter(x=>x.active).length}</b></div></div></div>`:empty('Sem destaque ainda');
 $('execRanking').innerHTML=execAgg.slice(0,7).map((x,i)=>`<div class="rank-row"><div class="rank-num">${i+1}</div><div><strong>${esc(x.name)}</strong><small>${esc(teamName(x.team_id))} • ${x.contracts} contratos • ${x.minutes} minutas</small></div><div class="rank-score">${x.score}</div></div>`).join('')||empty('Sem produção no período');renderQuizHealth()}
function renderTeams(){const rr=filteredReports();$('teamsGrid').innerHTML=teams.map(t=>{const leader=leaderForTeam(t.id),ex=execsOfTeam(t.id),tr=rr.filter(r=>r.team_id===t.id);return `<article class="team-card"><div class="team-card-head"><span class="pill ${t.active?'active':'inactive'}">${t.active?'ATIVO':'INATIVO'}</span><small>${ex.filter(x=>x.active).length} executivos ativos</small></div><h3>${esc(t.name)}</h3><p>Líder: <strong>${esc(leader?.name||'Não definido')}</strong><br>${esc(leader?.email||'')}</p><div class="team-meta"><div><small>Reuniões</small><b>${sum(tr,'meetings_held')}</b></div><div><small>Minutas</small><b>${sum(tr,'minutes_sent')}</b></div><div><small>Contratos</small><b>${sum(tr,'contracts_closed')}</b></div></div><div class="card-actions">${leader?`<button class="secondary" data-edit-leader="${leader.id}">Editar líder</button>`:''}</div></article>`}).join('')||empty('Nenhum time cadastrado');$$('[data-edit-leader]').forEach(b=>b.onclick=()=>openLeader(b.dataset.editLeader))}
function renderExecutives(){const term=($('execSearch').value||'').toLowerCase(),team=$('execTeamFilter').value||'',rr=filteredReports(),agg=aggregateByExec(rr);let list=profiles.filter(p=>p.role==='executive'&&(!team||p.team_id===team)&&(!term||[p.name,p.email].join(' ').toLowerCase().includes(term)));$('executivesTable').innerHTML=list.map(p=>{const m=agg.find(x=>x.id===p.id)||{scheduled:0,held:0,minutes:0,contracts:0};return `<div class="person-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.email)}</small></div><div><strong>${esc(teamName(p.team_id))}</strong><small><span class="pill ${p.active?'active':'inactive'}">${p.active?'ATIVO':'INATIVO'}</span></small></div><div class="person-metric"><b>${m.scheduled}</b><span>agendadas</span></div><div class="person-metric"><b>${m.held}</b><span>realizadas</span></div><div class="person-metric hide-tablet"><b>${m.minutes}</b><span>minutas</span></div><div class="person-metric hide-tablet"><b>${m.contracts}</b><span>contratos</span></div><div><button class="secondary" data-edit-exec="${p.id}">Editar</button></div></div>`}).join('')||empty('Nenhum executivo encontrado');$$('[data-edit-exec]').forEach(b=>b.onclick=()=>openExecutive(b.dataset.editExec))}
function latestSubmission(execId){return quizSubmissions.filter(s=>s.executive_id===execId).sort((a,b)=>new Date(b.submitted_at)-new Date(a.submitted_at))[0]}
function scoreSubmission(id){return avg(quizAnswers.filter(a=>a.submission_id===id).map(a=>num(a.score)))}
function renderQuizHealth(){const execs=profiles.filter(p=>p.role==='executive'&&p.active),latest=execs.map(e=>latestSubmission(e.id)).filter(Boolean);const scores=latest.map(s=>scoreSubmission(s.id));$('quizHealth').innerHTML=`<div class="quiz-health-grid"><div><span>Média geral</span><b>${avg(scores).toFixed(1)}</b></div><div><span>Avaliados</span><b>${latest.length}/${execs.length}</b></div><div><span>Ciclos realizados</span><b>${quizSubmissions.length}</b></div><div><span>Ponto crítico</span><b>${criticalTopic()?.avg?.toFixed(1)||'—'}</b></div></div>`}
function renderQuizExecFilter(){const team=$('quizTeamFilter')?.value||'',el=$('quizExecFilter');if(!el)return;const old=el.value;const list=profiles.filter(p=>p.role==='executive'&&(!team||p.team_id===team));el.innerHTML='<option value="">Todos os executivos</option>'+list.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if([...el.options].some(o=>o.value===old))el.value=old}
function selectedQuizSubmissions(){const team=$('quizTeamFilter')?.value||'',exec=$('quizExecFilter')?.value||'';const allowed=new Set(profiles.filter(p=>p.role==='executive'&&(!team||p.team_id===team)&&(!exec||p.id===exec)).map(p=>p.id));const latest=new Map();quizSubmissions.filter(s=>allowed.has(s.executive_id)).forEach(s=>{if(!latest.has(s.executive_id))latest.set(s.executive_id,s)});return [...latest.values()]}
function criticalTopic(selected=selectedQuizSubmissions()){const ids=new Set(selected.map(s=>s.id));const rows=quizQuestions.map(q=>{const scores=quizAnswers.filter(a=>ids.has(a.submission_id)&&a.question_id===q.id).map(a=>num(a.score));return {q,avg:avg(scores),n:scores.length}}).filter(x=>x.n).sort((a,b)=>a.avg-b.avg);return rows[0]}
function renderQuiz(){renderQuizExecFilter();const selected=selectedQuizSubmissions(),scores=selected.map(s=>scoreSubmission(s.id));$('quizSummary').innerHTML=`<article><span>Média do recorte</span><b>${avg(scores).toFixed(1)}</b></article><article><span>Executivos avaliados</span><b>${selected.length}</b></article><article><span>Total de ciclos</span><b>${quizSubmissions.length}</b></article>`;const ids=new Set(selected.map(s=>s.id));const topics=quizQuestions.map(q=>{const sc=quizAnswers.filter(a=>ids.has(a.submission_id)&&a.question_id===q.id).map(a=>num(a.score));return {q,avg:avg(sc),n:sc.length}}).filter(x=>x.n).sort((a,b)=>a.avg-b.avg).slice(0,8);$('criticalTopics').innerHTML=topics.map(x=>`<div class="topic-row"><div><strong>${esc(x.q.prompt)}</strong><small>${esc(x.q.section_label)} • ${x.n} respostas</small></div><div class="topic-score">${x.avg.toFixed(1)}</div></div>`).join('')||empty('Sem avaliações ainda');$('quizPeople').innerHTML=selected.map(s=>{const p=profiles.find(x=>x.id===s.executive_id);const all=quizSubmissions.filter(x=>x.executive_id===s.executive_id).sort((a,b)=>new Date(b.submitted_at)-new Date(a.submitted_at));const growth=all[1]?scoreSubmission(all[0].id)-scoreSubmission(all[1].id):null;return `<div class="quiz-person"><div><strong>${esc(p?.name||'Executivo')}</strong><small>${esc(teamName(p?.team_id))} • ciclo ${s.cycle_number}${growth!==null?' • evolução '+(growth>=0?'+':'')+growth.toFixed(1):''}</small></div><div class="quiz-person-score">${scoreSubmission(s.id).toFixed(1)}</div></div>`}).join('')||empty('Sem executivos avaliados')}
function bind(){ $$('.nav').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$('pageTitle').textContent={overview:'Visão geral',teams:'Times e líderes',executives:'Executivos',quiz:'Quiz e conhecimento'}[v]});$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});$('logout').onclick=async()=>{await client.auth.signOut();location.href='login.html'};$('refresh').onclick=loadAll;$('periodFilter').onchange=()=>{$('customDates').classList.toggle('hidden',$('periodFilter').value!=='custom');renderOverview();renderTeams();renderExecutives()};$('teamFilter').onchange=()=>{renderOverview();renderTeams();renderExecutives()};$('dateFrom').onchange=$('dateTo').onchange=()=>{renderOverview();renderTeams();renderExecutives()};$('execSearch').oninput=renderExecutives;$('execTeamFilter').onchange=renderExecutives;$('quizTeamFilter').onchange=()=>{renderQuizExecFilter();renderQuiz()};$('quizExecFilter').onchange=renderQuiz;$('teamForm').onsubmit=createTeam;$('leaderForm').onsubmit=saveLeader;$('executiveForm').onsubmit=saveExecutive}
function openModal(id){$(id).classList.add('open')}
async function edge(name,payload){const res=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':'Bearer '+session.access_token},body:JSON.stringify(payload)});const out=await res.json().catch(()=>({}));if(!res.ok)throw new Error(out.error||'Erro na operação');return out}
async function createTeam(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await edge('director-admin',{action:'create_team',team_name:$('teamName').value.trim(),leader_name:$('leaderName').value.trim(),email:$('leaderEmail').value.trim(),password:$('leaderPassword').value});$('teamForm').reset();$('teamModal').classList.remove('open');toast('Time e líder cadastrados.');await loadAll()}catch(err){toast(err.message)}btn.disabled=false}
function openLeader(id){const p=profiles.find(x=>x.id===id);if(!p)return;$('leaderId').value=p.id;$('editLeaderName').value=p.name;$('editLeaderEmail').value=p.email;$('editLeaderPassword').value='';$('editLeaderActive').checked=p.active;openModal('leaderModal')}
async function saveLeader(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{await edge('director-admin',{action:'update_leader',user_id:$('leaderId').value,name:$('editLeaderName').value.trim(),email:$('editLeaderEmail').value.trim(),password:$('editLeaderPassword').value,active:$('editLeaderActive').checked});$('leaderModal').classList.remove('open');toast('Líder atualizado.');await loadAll()}catch(err){toast(err.message)}btn.disabled=false}
function openExecutive(id){const p=profiles.find(x=>x.id===id);if(!p)return;$('editExecId').value=p.id;$('editExecName').value=p.name;$('editExecEmail').value=p.email;$('editExecTeam').value=p.team_id||'';$('editExecPassword').value='';$('editExecActive').checked=p.active;openModal('executiveModal')}
async function saveExecutive(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const id=$('editExecId').value,team=$('editExecTeam').value;await edge('admin-users',{action:'update',user_id:id,name:$('editExecName').value.trim(),email:$('editExecEmail').value.trim(),password:$('editExecPassword').value,team_id:team});await edge('admin-users',{action:'toggle',user_id:id,active:$('editExecActive').checked});$('executiveModal').classList.remove('open');toast('Executivo atualizado.');await loadAll()}catch(err){toast(err.message)}btn.disabled=false}
init();